### ISSUE TITLE
Brisk generate a SIGSEGV

### ISSUE THREAD

**Issue by natir** [Malfoy/Brisk#1]
Hi

I use brisk to count kmer in [another project](https://bitbucket.org/pierre_marijon/pangenie/src/brisk/) to use brisk I encapsulate in a [class](https://bitbucket.org/pierre_marijon/pangenie/src/brisk/src/briskcounter.cpp). When I run Pangenie I get a SIGSEV with this backtrace:

```
#0  0x00002aaaab7924b8 in __memcpy_ssse3_back () from /lib64/libc.so.6
#1  0x00000000004375c6 in SKCL::get_prefix(unsigned char const*, Parameters const&) const ()
#2  0x0000000000437866 in SKCL::param_interleaved_value(unsigned char*, unsigned char, Parameters const&) const ()
#3  0x0000000000437a74 in SKCL::interleaved_value(unsigned char*, Parameters const&) const ()
#4  0x00002aaaaaeb1a4f in Bucket<unsigned char>::insert_buffer() () from /home/marijon/tools/pangenie/build/src/libPanGenieLib.so
#5  0x00002aaaaaeb0959 in Bucket<unsigned char>::insert_kmer(kmer_full&) () from /home/marijon/tools/pangenie/build/src/libPanGenieLib.so
#6  0x00002aaaaaeafe66 in DenseMenuYo<unsigned char>::insert_kmer(kmer_full&) () from /home/marijon/tools/pangenie/build/src/libPanGenieLib.so
#7  0x00002aaaaaeaf6de in Brisk<unsigned char>::insert(kmer_full&) () from /home/marijon/tools/pangenie/build/src/libPanGenieLib.so
#8  0x00002aaaaaeae323 in BriskIndex::BriskIndex(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, unsigned long, unsigned long, unsigned long, unsigned long) () from /home/marijon/tools/pangenie/build/src/libPanGenieLib.so
#9  0x0000000000439b03 in main ()
```

I can provide a file of sequence that I am trying to index. I use the commit 84a8ce254cf8

Thank for your work.

**Comment by yoann-dufresne** [comment]
Thanks for the outcome.
Brisk is still under construction, that's why.

We should release a new version during January with a lot of code changes.
Hope it will correct your problem. If not, please contact me again.
